// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppNav: typeof import('./components/AppNav.vue')['default']
    Button: typeof import('daisy-ui-kit')['Button']
    Card: typeof import('daisy-ui-kit')['Card']
    CardBody: typeof import('daisy-ui-kit')['CardBody']
    CardTitle: typeof import('daisy-ui-kit')['CardTitle']
    DaisyButton: typeof import('daisy-ui-kit')['DaisyButton']
    DaisyButtonGroup: typeof import('daisy-ui-kit')['DaisyButtonGroup']
    DaisyCard: typeof import('daisy-ui-kit')['DaisyCard']
    DaisyCardBody: typeof import('daisy-ui-kit')['DaisyCardBody']
    DaisyCardTitle: typeof import('daisy-ui-kit')['DaisyCardTitle']
    DaisyDropdown: typeof import('daisy-ui-kit')['DaisyDropdown']
    DaisyDropdownContent: typeof import('daisy-ui-kit')['DaisyDropdownContent']
    DaisyFlex: typeof import('daisy-ui-kit')['DaisyFlex']
    DaisyFormControl: typeof import('daisy-ui-kit')['DaisyFormControl']
    DaisyHero: typeof import('daisy-ui-kit')['DaisyHero']
    DaisyHeroContent: typeof import('daisy-ui-kit')['DaisyHeroContent']
    DaisyLabel: typeof import('daisy-ui-kit')['DaisyLabel']
    DaisyLabelTextAlt: typeof import('daisy-ui-kit')['DaisyLabelTextAlt']
    DaisyLink: typeof import('daisy-ui-kit')['DaisyLink']
    DaisyMenu: typeof import('daisy-ui-kit')['DaisyMenu']
    DaisyMenuItem: typeof import('daisy-ui-kit')['DaisyMenuItem']
    DaisyNavbar: typeof import('daisy-ui-kit')['DaisyNavbar']
    DaisyNavbarCenter: typeof import('daisy-ui-kit')['DaisyNavbarCenter']
    DaisyNavbarEnd: typeof import('daisy-ui-kit')['DaisyNavbarEnd']
    DaisyNavbarStart: typeof import('daisy-ui-kit')['DaisyNavbarStart']
    DaisySelect: typeof import('daisy-ui-kit')['DaisySelect']
    DaisyText: typeof import('daisy-ui-kit')['DaisyText']
    DaisyTextInput: typeof import('daisy-ui-kit')['DaisyTextInput']
    DaisyTooltip: typeof import('daisy-ui-kit')['DaisyTooltip']
    Flex: typeof import('daisy-ui-kit')['Flex']
    FormControl: typeof import('daisy-ui-kit')['FormControl']
    FormControlText: typeof import('./components/FormControlText.vue')['default']
    Hero: typeof import('daisy-ui-kit')['Hero']
    HeroContent: typeof import('daisy-ui-kit')['HeroContent']
    Link: typeof import('daisy-ui-kit')['Link']
    Loading: typeof import('./components/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('daisy-ui-kit')['Select']
    Text: typeof import('daisy-ui-kit')['Text']
  }
}
